spring.application.name=authcentral

server.port=8080

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3307/authcentral
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/app-realm

# Keycloak Admin
keycloak.server-url=http://localhost:8181
keycloak.realm=app-realm
keycloak.client-id=spring-client
keycloak.client-secret=secret
keycloak.admin.username=admin
keycloak.admin.password=admin

# Jackson
